import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { API_URL } from '../../Api';
import { Link } from 'react-router-dom';
import './DownCertificate.css';

const DownCertificate = () => {
  const [certificates, setCertificates] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterStatus, setFilterStatus] = useState('all');

  // Fetch logged in user's applications & certificates
  const fetchUserCertificates = async () => {
    try {
      setLoading(true);
      const stored = localStorage.getItem('user');
      let user = null;
      if (stored) {
        try {
          user = JSON.parse(stored);
        } catch (e) {}
      }

      const token = localStorage.getItem('token');
      const headers = token ? { Authorization: `Bearer ${token}` } : {};
      const params = {};
      if (user) {
        if (user.email) params.email = user.email;
        if (user.id || user._id) params.userId = user.id || user._id;
        if (user.uniqueId) params.uniqueId = user.uniqueId;
      }

      const res = await axios.get(`${API_URL}/uru/user`, { headers, params });
      const list = res.data?.data || [];

      if (Array.isArray(list) && list.length > 0) {
        const mapped = list.map((item) => {
          const isPaid = item.paymentStatus === 'Paid' || item.paymentStatus === 'Success' || item.status === 'Paid';
          const hasCert = Boolean(item.certificateUrl && item.certificateUrl.trim().length > 0);
          const isPub = Boolean(item.isPublished || item.published);

          // Status determination: Ready when certificate is uploaded
          let status = 'verifying';
          if (hasCert) {
            status = 'ready';
          } else if (isPaid) {
            status = 'verifying';
          } else {
            status = 'verifying';
          }

          return {
            id: item.appNo || item.applicationNumber || `URU${item._id?.slice(-4)}`,
            _id: item._id || item.id,
            applicantName: item.applicantName || item.name || user?.name || user?.fullName || 'Applicant',
            applicationDate: item.date || (item.createdAt ? new Date(item.createdAt).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : 'Recent'),
            category: item.position || item.category || 'Unique Record',
            certificateUrl: item.certificateUrl || '',
            isPublished: isPub,
            feePaid: isPaid,
            status,
          };
        });

        setCertificates(mapped);
      } else {
        setCertificates([]);
      }
    } catch (err) {
      console.error('Error fetching user certificates:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchUserCertificates();
  }, []);

  // Handle Certificate Download Action
  const handleDownload = (cert) => {
    if (!cert.certificateUrl) {
      alert(`Certificate for Application No: ${cert.id} is being generated by the URU records verification team. Please check back shortly.`);
      return;
    }

    // Trigger download / open certificate
    window.open(cert.certificateUrl, '_blank', 'noopener,noreferrer');

    setCertificates((prev) =>
      prev.map((c) => (c.id === cert.id ? { ...c, status: 'downloaded' } : c))
    );
  };

  const filteredCertificates = certificates.filter((cert) => {
    const term = searchTerm.toLowerCase();
    const matchesSearch =
      cert.id.toLowerCase().includes(term) ||
      cert.applicantName.toLowerCase().includes(term) ||
      cert.category.toLowerCase().includes(term);

    const matchesFilter =
      filterStatus === 'all' ||
      (filterStatus === 'ready' && (cert.status === 'ready' || cert.status === 'downloaded')) ||
      (filterStatus === 'verifying' && cert.status === 'verifying');

    return matchesSearch && matchesFilter;
  });

  return (
    <div className="dc-dashboard-container">
      {/* Header Banner Section */}
      <header className="dc-header-section">
        <div className="dc-header-content">
          <span className="dc-badge-pill">✨ Official Archives</span>
          <h1 className="dc-main-title">Download Your Certificates</h1>
          <p className="dc-main-subtitle">
            Track your application status, complete verifications, and instantly download your secure digital recognition certificates.
          </p>
        </div>

        {/* Filter and Search Bar */}
        <div className="dc-controls-bar">
          <div className="dc-search-box">
            <svg className="dc-search-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <circle cx="11" cy="11" r="8" /><path d="m21 21-4.3-4.3" />
            </svg>
            <input
              type="text"
              placeholder="Search by Application No or Name..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
          <div className="dc-filter-tabs">
            <button
              className={`dc-filter-tab ${filterStatus === 'all' ? 'active' : ''}`}
              onClick={() => setFilterStatus('all')}
            >
              All ({certificates.length})
            </button>
            <button
              className={`dc-filter-tab ${filterStatus === 'ready' ? 'active' : ''}`}
              onClick={() => setFilterStatus('ready')}
            >
              Ready ({certificates.filter((c) => c.status === 'ready' || c.status === 'downloaded').length})
            </button>
            <button
              className={`dc-filter-tab ${filterStatus === 'verifying' ? 'active' : ''}`}
              onClick={() => setFilterStatus('verifying')}
            >
              Verifying ({certificates.filter((c) => c.status === 'verifying').length})
            </button>
          </div>
        </div>
      </header>

      {/* Certificates Grid Section */}
      <section className="dc-cards-grid-section">
        {loading ? (
          <div className="dc-empty-state" style={{ padding: '60px 20px', gridColumn: '1 / -1' }}>
            <div className="as-modal__spinner" style={{ margin: '0 auto 16px', width: '36px', height: '36px' }}></div>
            <h3>Loading your certificates...</h3>
          </div>
        ) : filteredCertificates.length > 0 ? (
          filteredCertificates.map((cert) => (
            <div className={`dc-cert-card ${cert.status}`} key={cert.id}>
              {/* Card Top Status Indicator */}
              <div className="dc-card-top-row">
                <span className={`dc-status-badge ${cert.status}`}>
                  {cert.status === 'verifying' && '⏳ Under Verification'}
                  {cert.status === 'ready' && '✅ Ready to Download'}
                  {cert.status === 'downloaded' && '📥 Downloaded'}
                </span>
                <span className="dc-category-tag">{cert.category}</span>
              </div>

              {/* Main Card Header */}
              <div className="dc-card-header">
                <h3 className="dc-card-title">Official Recognition Certificate</h3>
                <div className="dc-app-no-chip">
                  Application No: <strong>{cert.id}</strong>
                </div>
              </div>

              {/* Application Details Meta */}
              <div className="dc-card-meta">
                <div className="dc-meta-item highlight-border">
                  <span className="dc-meta-label">Application Date:</span>
                  <span className="dc-meta-value">{cert.applicationDate}</span>
                </div>
                <div className="dc-meta-item">
                  <span className="dc-meta-label">Applicant Name:</span>
                  <span className="dc-meta-value name">{cert.applicantName}</span>
                </div>
              </div>

              {/* Descriptive Notice */}
              <p className="dc-card-desc">
                {cert.status === 'verifying'
                  ? cert.feePaid
                    ? 'Payment received! Your official certificate is being generated and approved by the records jury. It will be enabled here upon upload & publish.'
                    : 'After verification, acceptance, and successful receipt of the prescribed fee, the button to download your digital certificate will be enabled. Please wait till then.'
                  : 'Your verification is successfully completed and approved. You can now download your verified digital certificate instantly.'}
              </p>

              {/* Animated Download Icon Graphic */}
              <div className={`dc-icon-circle-wrap ${cert.status}`}>
                <div className="dc-pulse-ring"></div>
                <div className="dc-download-icon-box">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                    <polyline points="7 10 12 15 17 10" />
                    <line x1="12" y1="15" x2="12" y2="3" />
                  </svg>
                </div>
              </div>

              {/* Action Button */}
              <div className="dc-card-action">
                {cert.status === 'verifying' ? (
                  <button type="button" className="dc-btn dc-btn-verifying" disabled>
                    <span className="dc-spinner"></span> Verification / Publish In Progress
                  </button>
                ) : cert.status === 'ready' ? (
                  <button type="button" className="dc-btn dc-btn-download" onClick={() => handleDownload(cert)}>
                    Download Certificate 📥
                  </button>
                ) : (
                  <button type="button" className="dc-btn dc-btn-downloaded" onClick={() => handleDownload(cert)}>
                    Download Again 🔄
                  </button>
                )}
              </div>
            </div>
          ))
        ) : (
          <div className="dc-empty-state" style={{ gridColumn: '1 / -1' }}>
            <div className="dc-empty-icon">📂</div>
            <h3>No certificates found</h3>
            <p style={{ maxWidth: '420px', margin: '0 auto 20px', color: '#64748b' }}>
              {certificates.length === 0
                ? "You haven't submitted any applications yet. Apply online to get your achievements certified."
                : 'Try adjusting your search query or filter criteria.'}
            </p>
            {certificates.length === 0 && (
              <Link
                to="/uru/apply"
                style={{
                  display: 'inline-block',
                  background: 'linear-gradient(135deg, #7c3aed, #4f46e5)',
                  color: '#ffffff',
                  padding: '10px 24px',
                  borderRadius: '8px',
                  fontWeight: 600,
                  textDecoration: 'none',
                }}
              >
                Apply Online Now 🚀
              </Link>
            )}
          </div>
        )}
      </section>
    </div>
  );
};

export default DownCertificate;